void DEFAULT_INITIALIZATION() {
  CONTROL_TABLE_STATIC[API_SERVER] = "https://cisea.bukitasam.co.id/api-iot/api/v1/rain_sensor/post";
  CONTROL_TABLE_STATIC[SSID] = "Detector-Vibration";
  CONTROL_TABLE_STATIC[PASSWORD] = "@DV2023_";
  CONTROL_TABLE_STATIC[NTP_SERVER] = "pool.ntp.org";

  CONTROL_TABLE_DINAMIC[UUID] = "b28eaf0c-449b-481d-8a31-9b8b3a7f3c14";
  CONTROL_TABLE_DINAMIC[API_OTA] = "https://s3.bukitasam.co.id/public/rain-detector/esp32/" + String(CONTROL_TABLE_DINAMIC[UUID]) + "/" + String(CONTROL_TABLE_DINAMIC[UUID]) + ".ino.esp32.bin";
  CONTROL_TABLE_DINAMIC[TIMESTAMP] = "2022-12-12 10:10:10";
  CONTROL_TABLE_DINAMIC[GPS_TS] = "2022-12-12 10:10:10";
  CONTROL_TABLE_DINAMIC[STATUS_ERROR] = "";

  CONTROL_TABLE_DIGITAL[BUTTON_SELECT] = 0;
  CONTROL_TABLE_DIGITAL[BUTTON_ENTER] = 0;
  CONTROL_TABLE_DIGITAL[STATE_MENU] = 0;
  CONTROL_TABLE_DIGITAL[DAYLIGHT] = 0;

  CONTROL_TABLE_STATE[RUNMODE] = true;
  CONTROL_TABLE_STATE[SENDING] = true;
  CONTROL_TABLE_STATE[RESTART] = false;
  CONTROL_TABLE_STATE[INTERRUPT_BUTTON] = false;
  CONTROL_TABLE_STATE[SELECT_MODE] = true;
  CONTROL_TABLE_STATE[OTA] = false;
  CONTROL_TABLE_STATE[CALIBRATE] = false;
  CONTROL_TABLE_STATE[PRINT_DATA] = true;
  CONTROL_TABLE_STATE[ISCALIBRATED] = true;
  CONTROL_TABLE_STATE[PRINT_ALL_DATA] = false;
  CONTROL_TABLE_STATE[GET_NTP] = true;

  CONTROL_TABLE_TIME[SENDING_TO_SERVER] = 30000;
  CONTROL_TABLE_TIME[READ_ALL_SENSOR] = 2000;
  CONTROL_TABLE_TIME[SET_MPU_SENSOR] = 25;
  CONTROL_TABLE_TIME[SET_VIB_SENSOR] = 250;
  CONTROL_TABLE_TIME[SET_GPS_SENSOR] = 100;
  CONTROL_TABLE_TIME[READ_BUTTON] = 50;
  CONTROL_TABLE_TIME[OLED] = 1000;
  CONTROL_TABLE_TIME[SET_CALIBRATE] = 100;
  CONTROL_TABLE_TIME[SET_NTP] = 1000;
  CONTROL_TABLE_TIME[OFFSET] = 25200;

  CONTROL_TABLE_GPS[LATITUDE] = 0.00;
  CONTROL_TABLE_GPS[LONGITUDE] = 0.00;
  CONTROL_TABLE_GPS[SPEED_KMPH] = 0.00;
  CONTROL_TABLE_GPS[SPEED_MPH] = 0.00;
  CONTROL_TABLE_GPS[ALTITUDE] = 0.00;

  CONTROL_TABLE_VIBRATION[DIGITAL_SW420] = 0;
  CONTROL_TABLE_VIBRATION[ANALOG_VIB] = 0;
  CONTROL_TABLE_VIBRATION[DIGITAL_VIB] = 0;
  CONTROL_TABLE_VIBRATION[ANALOG_PIEZO] = 0;

  CONTROL_TABLE_MPU[ACC_X] = 0.0;
  CONTROL_TABLE_MPU[ACC_Y] = 0.0;
  CONTROL_TABLE_MPU[ACC_Z] = 0.0;
  CONTROL_TABLE_MPU[GYRO_X] = 0.0;
  CONTROL_TABLE_MPU[GYRO_Y] = 0.0;
  CONTROL_TABLE_MPU[GYRO_Z] = 0.0;
  CONTROL_TABLE_MPU[MAG_X] = 0.0;
  CONTROL_TABLE_MPU[MAG_Y] = 0.0;
  CONTROL_TABLE_MPU[MAG_Z] = 0.0;
  CONTROL_TABLE_MPU[QUAN_X] = 0.0;
  CONTROL_TABLE_MPU[QUAN_Y] = 0.0;
  CONTROL_TABLE_MPU[QUAN_Z] = 0.0;
  CONTROL_TABLE_MPU[QUAN_W] = 0.0;
  CONTROL_TABLE_MPU[ROLL] = 0.0;
  CONTROL_TABLE_MPU[PITCH] = 0.0;
  CONTROL_TABLE_MPU[YAW] = 0.0;
  CONTROL_TABLE_MPU[EULER_X] = 0.0;
  CONTROL_TABLE_MPU[EULER_Y] = 0.0;
  CONTROL_TABLE_MPU[EULER_Z] = 0.0;
  CONTROL_TABLE_MPU[LIN_ACC_X] = 0.0;
  CONTROL_TABLE_MPU[LIN_ACC_Y] = 0.0;
  CONTROL_TABLE_MPU[LIN_ACC_Z] = 0.0;
  CONTROL_TABLE_MPU[ACC_BIAS_X] = 0.0;
  CONTROL_TABLE_MPU[ACC_BIAS_Y] = 0.0;
  CONTROL_TABLE_MPU[ACC_BIAS_Z] = 0.0;
  CONTROL_TABLE_MPU[GYRO_BIAS_X] = 0.0;
  CONTROL_TABLE_MPU[GYRO_BIAS_Y] = 0.0;
  CONTROL_TABLE_MPU[GYRO_BIAS_Z] = 0.0;
  CONTROL_TABLE_MPU[MAG_BIAS_X] = 0.0;
  CONTROL_TABLE_MPU[MAG_BIAS_Y] = 0.0;
  CONTROL_TABLE_MPU[MAG_BIAS_Z] = 0.0;
  CONTROL_TABLE_MPU[MAG_SCALE_X] = 0.0;
  CONTROL_TABLE_MPU[MAG_SCALE_Y] = 0.0;
  CONTROL_TABLE_MPU[MAG_SCALE_Z] = 0.0;
  CONTROL_TABLE_MPU[TEMPERATURE] = 0.0;
  CONTROL_TABLE_MPU[ISCONNECTED] = 0;
}

void CALIBRATE_MPU() {
  bool Calibrated = true;
  if (Calibrated) {
    Serial.println("Calibrate MPU");
    // calibrate anytime you want to
    Serial.println("Accel Gyro calibration will start in 5sec.");
    Serial.println("Please leave the device still on the flat plane.");
    mpu.verbose(true);
    delay(5000);
    mpu.calibrateAccelGyro();

    Serial.println("Mag calibration will start in 5sec.");
    Serial.println("Please Wave device in a figure eight until done.");
    delay(5000);
    mpu.calibrateMag();
    mpu.verbose(false);
    EEPROM.write(0, true);
    EEPROM.commit();
  }
}

void CHECK_ERROR() {
  bool restart = CONTROL_TABLE_STATE[STATUS_ERROR];
  if (restart) {
    //*
    CONTROL_TABLE_DINAMIC[STATUS_ERROR] += "\n Restart On 5 Seconds";
    display.display();
    display.clearDisplay();
    display.setCursor(0, 0);
    display.println(CONTROL_TABLE_DINAMIC[STATUS_ERROR]);
    delay(5000);
    //*/
    Serial.print(CONTROL_TABLE_DINAMIC[STATUS_ERROR]);
  }
}
